cargo-features = ["edition"]

[package]
name = "saturn_types"
version = "0.1.0"
authors = ["Arthur Goldman <arthur@goldman-tribe.org>"]
edition = "2018"
license = "MIT"

[dependencies]
failure = "^0.1"
failure_derive = "^0.1"
saturn_tagging = { git = "https://github.com/gefjon/saturn_tagging" }
